INSERT INTO economic_indicators (
    country_code, 
    year, 
    FDI_Net_CurrentUD, 
    FDI_NetInflows_PercentGDP, 
    FDI_NetInflows_CurrentUD, 
    FDI_NetOutflows_PercentGDP, 
    FDI_NetOutflows_CurrentUD, 
    GDP_CurrentUD, 
    GDP_Growth_Percent, 
    General_government_final_consumption_expenditure_CurrentUD, 
    Gini_Index, 
    Gross_National_Expenditure_CurrentUD, 
    Inflation_ConsumerPrices_AnnualPercent, 
    Inflation_GDPDeflator_AnnualPercent, 
    Inflation_GDPDeflator_AnnualPercent_LinkedSeries, 
    MilitaryExpenditure_CurrentUD, 
    Net_Trade_Goods_CurrentUD, 
    Net_Trade_GoodsandServices_CurrentUD, 
    Trade_PercentGDP, 
    TradeServices_PercentGDP
)
SELECT 
    country_code, 
    year,
    MAX(CASE WHEN series_name = 'Foreign direct investment, net (BoP, current US$)' THEN value END) AS FDI_Net_CurrentUD,
    MAX(CASE WHEN series_name = 'Foreign direct investment, net inflows (% of GDP)' THEN value END) AS FDI_NetInflows_PercentGDP,
    MAX(CASE WHEN series_name = 'Foreign direct investment, net inflows (BoP, current US$)' THEN value END) AS FDI_NetInflows_CurrentUD,
    MAX(CASE WHEN series_name = 'Foreign direct investment, net outflows (% of GDP)' THEN value END) AS FDI_NetOutflows_PercentGDP,
    MAX(CASE WHEN series_name = 'Foreign direct investment, net outflows (BoP, current US$)' THEN value END) AS FDI_NetOutflows_CurrentUD,
    MAX(CASE WHEN series_name = 'GDP (current US$)' THEN value END) AS GDP_CurrentUD,
    MAX(CASE WHEN series_name = 'GDP growth (annual %)' THEN value END) AS GDP_Growth_Percent,
    MAX(CASE WHEN series_name = 'General government final consumption expenditure (current US$)' THEN value END) AS General_government_final_consumption_expenditure_CurrentUD,
    MAX(CASE WHEN series_name = 'Gini index' THEN value END) AS Gini_Index,
    MAX(CASE WHEN series_name = 'Gross national expenditure (current US$)' THEN value END) AS Gross_National_Expenditure_CurrentUD,
    MAX(CASE WHEN series_name = 'Inflation, consumer prices (annual %)' THEN value END) AS Inflation_ConsumerPrices_AnnualPercent,
    MAX(CASE WHEN series_name = 'Inflation, GDP deflator (annual %)' THEN value END) AS Inflation_GDPDeflator_AnnualPercent,
    MAX(CASE WHEN series_name = 'Inflation, GDP deflator: linked series (annual %)' THEN value END) AS Inflation_GDPDeflator_AnnualPercent_LinkedSeries,
    MAX(CASE WHEN series_name = 'Military expenditure (current USD)' THEN value END) AS MilitaryExpenditure_CurrentUD,
    MAX(CASE WHEN series_name = 'Net trade in goods (BoP, current US$)' THEN value END) AS Net_Trade_Goods_CurrentUD,
    MAX(CASE WHEN series_name = 'Net trade in goods and services (BoP, current US$)' THEN value END) AS Net_Trade_GoodsandServices_CurrentUD,
    MAX(CASE WHEN series_name = 'Trade (% of GDP)' THEN value END) AS Trade_PercentGDP,
    MAX(CASE WHEN series_name = 'Trade in services (% of GDP)' THEN value END) AS TradeServices_PercentGDP
FROM temp_economic_indicators
GROUP BY country_code, year;
